sudo: required

services:
  - docker

env:
  global:
    - DOCKER_USER=dnissimi
#   - DOCKER_PASS=<secure: ...>
    - secure: "IWDbV4hv8WLWVBs6hgdnNp+whmF6UQ7rFbhzqo80HUXCs7+VGE8yljvawxrTNOePj2H3v/KPPnDApxUJK6l2VpUeejg5EglNKWF20NJ3MOT9i7N6DjP4LEWFdS7XU9uueVGgNzgrBIdRvIwbRHQg3MCA6L35Gl9twCLg3zOk/wkiyDY5DYoJoA58vNjAXtHnHRwPyPSZk7DAJl28KhncR0GZXSIUU5XZcv+uQBsfIBxRKVf1sPe/uOoAtpP9JcBFTjFXog6AyrobHjj3NSvRuejw+wLFYexBr3Z1THWfqyOjXi6cy/P+U9zzdZXtgLVMV/X16NFXI6PV4fW9VUr5QbFShE4xZa8Fefybqa+dtnErA17PUaP9KMwgmSNCttYDmntTCNtYRSIZn5g2cTT5v4nAG8CjwAnQPHd72t1VzLCkkVYS8eB5B+poW9CYi86QeumVmCLLTjtvOjR2l/ig9eIQNsR2pbzW5rMAWDitdpZk4dPqynvlOLYdNnEyWz9XPQv5HNeNdM8UOLRFgP0dVbJG984Sj9cWCr2VatOSfVWyM1Mg4T3JUAN5VGOpUZjSnduV6HTOJ/i0UnzF362/rVpqx8Ntg7VoVIfMmD9+Z9FtcZwZUJXbL9fiRi+5HFtKbIol+mQ1dy1H0r8SOfsnTtDA4Uj1QCPFyPJ22eAyF5U="


script:
  - docker build -t dnissimi/devops-exercise .
  - docker run -d dnissimi/devops-exercise

after_script:
  - docker images
  - coverage erase
  - coverage run test/test-http.py "http://127.0.0.1:8080/api/v1/about" && coverage html

after_success:
  - codecov

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  provider: script
  script: docker push dnissimi/devops-exercise
  on:
    branch: master
