sudo: required

language: python

python:
# - 2.7
# - 3.5
  - 3.6

services:
  - docker

env:
  global:

install: 
  - pip install -r requirements/dev.txt

script:
  - docker build -t dnissimi/devops-exercise .
  - docker run -d -p 8080:8080 dnissimi/devops-exercise

#after_script:
  - docker images
  - docker ps
  - sleep 5
  - coverage erase
  - coverage run test/test-http.py "http://127.0.0.1:8080/api/v1.0/about" && coverage html

after_success:
  - codecov

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

deploy:
  provider: script
  script: docker push dnissimi/devops-exercise
  on:
    branch: master
