sudo: required

services:
  - docker

env:
  global:
    - REGISTRY_USER=dnissimi
#   - REGISTRY_PASS=<secure: ...>
    - secure: "Gwwovotqw2k0MebOFGcergkfl8qP/Ip//DL3CbYCaAmh/bc6KPD8DXxmjqz0HvWFdkjt1rpBVlw3rNHkoLPVofcZO0zHPF0v/GmBXPQdq03iXT/Lwc8DypmFBVqygaWIF6qN5/lSZLomzJQENcyGeoeFW4nMszCBh+9SBDCQeB88d+nfcKkWPO3sgDy0p1Vwp4Jar5FduD8YYD1QZnCsOM/BPl6zczxvCgUKfv17KJgOUWY8GgC7cTpVEcEqtoS3chRB6RUl/TOvWNucMxnY0bpb10uCXK+hoLjnPCecMhbTzZgXbOU8fTv6N/3BYJmc41nmnJ7VqbS37tG80HP0QTBIEmWCslbNo+YAMl/b6E0Khu318PplaZ0FbnE2O3vVcSHSbfA87AD570aNL5as1LW9xLXvddWP60Mh0Ehzp9haUPd60N+mQV3AuyUlEzrfkks1nUwVd0A+9XeMwiP+1zbprgfbgz9HOyhg6AHyZlI+aoC5KEhg4yUU2i43K4F+ulhBpCJtoiREvQB1Y6FWFFPId9rYYLqobYKcSNR0hkrdjiK+QwSvYzgVmDQuyLmynirtgmXVYU61uzWYGMx/SuYXDprTkXrcl9HDUA4BTecIKul/QWMy08aOlGWZvVu5NfKbK/PMxNgJCsfmIc+W6xk9BUdJOAaRzrHIc6Syz6c="


script:
  - docker build -t dnissimi/devops-exercise .
  - docker run -d dnissimi/devops-exercise

after_script:
  - docker images
  - coverage erase
  - coverage run test/test-http.py "http://127.0.0.1:8080/api/v1/about" && coverage html

after_success:
  - codecov

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push dnissimi/devops-exercise
  on:
    branch: master
