language: python

python:
    - 2.7
#    - 3.5
#    - 3.6

install: 
   - pip install -r requirements/dev.txt
#   - pip install codecov

#start app
before_script:
#   - export FLASK_APP="$TRAVIS_BUILD_DIR/application.py"
   - export FLASK_DEBUG=1
   - python application.py &

# unit test http 200
script:	
#   - coverage erase
#   - coverage run test/test-http.py "http://127.0.0.1:8080/api/v1/about" && coverage html
   - python test/test-http.py "http://127.0.0.1:8080/api/v1/about"


after_success:
#   - codecov
