sudo: required

services:
  - docker

env:
  global:
    - DOCKER_USER=dnissimi
#   - DOCKER_PASS=<secure: ...>
    - secure: "Wj4Tvu187lxvQO251x4GNZ77Ha1j0rNLr9DJTcIu4r+kWg6CzWiDqGWAYwTnRGwhtqt7FHKg43GQYpTr4MNpWjZyf1/o3BmF5BjIYemT1gxiXvE7DuztMkU8z9wvQaWDRWS0Xmraj/DXJBVedUIc65IAlfXQlzcCBCWp1/oeSy68/zhRw++XUkYrHW1utcVR+JFGAMGXsBBaAT1JoK9uUzgeITnUa7DEfoyftV1gFMsk0f8tbqNzA1vSwmerOQ7ryLjo5uVgKV1ivbHaN1P8uf4ut6UEzEjg61sbdRCKL9hbzIU41eb3ZvbwXmBgONAp9bv1N7hy7xG7Yg6pNfsUAbHQZ/oGBz1vludV3DbJzqYqxblzMBo9SbByQEv09MGqQ5gl5aPOtT5ogqk77RQf4K0v+Pil/E205LTl0/S7pPlu2lnNwNdHhkQmTGTYa8l5K7PKqNJpTKhrynLQ5Tb0aHnhWUn21R1Np4Ga+JP3IeyLBZ4ta7LsgPaWyM5AaWP3835TzTKD7QrktcnwVVuqNCyAARAEJAEG5ZCpMP9cC606ZGDPo1aPc4P46saOXep3LfQnBQfA2St0YpkjxRiTq61u3VaGIT5Ki7Ble2VNfSdKEgRIrp+9DRJLdrQQBizsFzU+7kMc2xONGD+GbJrZ5IB/mpJNa85mQgz6unAPXFo="


script:
  - docker build -t dnissimi/devops-exercise .
  - docker run -d dnissimi/devops-exercise

after_script:
  - docker images
  - coverage erase
  - coverage run test/test-http.py "http://127.0.0.1:8080/api/v1/about" && coverage html

after_success:
  - codecov

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  provider: script
  script: docker push dnissimi/devops-exercise
  on:
    branch: master
