sudo: required

services:
  - docker

env:
  global:
    - DOCKER_USER=dnissimi
#   - DOCKER_PASS=<secure: ...>
    - secure: "WuLAYbl4WQOhc82T3JvoSTumpDCsRKRSY3iCvI0+O0ABaU9OgNTp5DjcuqDinasN7hiOlFsABBFBVw+e4YHODWd2YsmWsUV/NqMlcniUGCa1t9cbCVHGamJ6CVj9HxMGqqUpWDG8hr/+mZRwYaFO7cQUEHT5AgX3r3jemTG1tcvpxSD/SjbTRtUo/FHdsY8TZGl8TgB9NJ17joZi9j5LyQETVxBsB7ZTxXxvDZ6SR2gKmL4/jXXff7zRhzEAsp4rd424tIfW3t1lUtZ0stlgjJAnEipkvEcIavmJWnD/u3NvkUTiupbVOeQwvze407U8x3uZzItmKrfalDaG3eg2I2X3LyCiqp7aAPjkjn4ilcPmOizS/Px6szPZ6bquJNQ3pFgBVNsitfAQqEhyN0UOm9OtZOlJLbZCT+nhlPKNQN+2wMfHb0Q9Vu6wGEGVlCsmCdCpVcCeFDMYqCokwPdrDVKzKSfAmK6XCmZiEFTFkLeNUcqyp9sqH+lCovUclh4FJLU+VDHP+msN3/CzSok/+GFDPIMQdCF9ix4nrzN7FRBH8x1+PDaOr5/oB+ZvWxn1ShziTgIp2jrTbU4MlOQRdkfGq1sB0oASKvqfrG+FLsuWM29qtuDwE3CacMYMyPYNg8/yZKzbP0En5Mdji5oWbU3SSIUow1XcKQm8uR4llPU="


script:
  - docker build -t dnissimi/devops-exercise .
  - docker run -d dnissimi/devops-exercise

after_script:
  - docker images
  - coverage erase
  - coverage run test/test-http.py "http://127.0.0.1:8080/api/v1/about" && coverage html

after_success:
  - codecov

before_deploy:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASS"

deploy:
  provider: script
  script: docker push dnissimi/devops-exercise
  on:
    branch: master
