sudo: required
language: python
python:
- 3.6
services:
- docker
env:
  secure: bueAKs2o6zYgMYQBKRYShkFVCFeypV/7ml2FEUOhJvlSPhguY6qNRxHwrT1FBomC3ECr/Z6gE2F0lXy1h/GrC+ESsabEyYxO0goyxyNTB58eJNdafQPCYZlDnwSMvWbRJPCGG0VZu/XHbEfGppyHxFLiryS2Yjx3cf7sa/N/mtLQMpo+dd6aIHf+JW6e7gnBI1zkEtBZBJzEHUqmQ7QGkAWU2jThoeJM5qYg73MmLpwbdWcuJD+8rXm8PHlABRjn5NJsajHgEy1w5Js5YT2tXIWt8cFMXO9hgnl1K0FYIsNO3wYtBU+ZGqwkMcqdfAIh/uk5XVRoDvXIZVDOjMpMhJ2wIZCsbk72TjkUUjoBMB3uyOLiHVGg65JgYMIg3E3svt89lLhPE8X0NPV7TAlScCx0K6lkHqAkiQBojgD846TOroHN/hg7I49RcelZM+OPfYdCb/sETCIVwamL3Jad6gdKJ5GpikPZdHr8PpAi8MsnOqrQEKwjUYop4pRDNTIjTceNBvE3n4A2HOKthyZD/DAWCKlGWmYW9Nmw8bXlzm/zKB2nLN80b+FNB3Udc9svV3ZNmxOfR0K/zhYoRYF094GFOLViYaO3dKdlCu9mI760WjeMgMYIM4BPCDE/l12vLn7SMM5VN+ZHNfw3MMkEN3sjjl/pOANvWsGu56jRv8c=
install:
- pip install -r requirements/dev.txt
script:
- docker build -t dnissimi/devops-exercise .
- docker run -d -p 8080:8080 dnissimi/devops-exercise
- docker images
- docker ps
- sleep 5
- coverage erase
- coverage run test/test-http.py "http://127.0.0.1:8080/api/v1.0/about" && coverage
  html
after_success:
- codecov
before_deploy:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  provider: script
  script: docker push dnissimi/devops-exercise
  on:
    branch: master
